# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWd(object):
    def setupUi(self, LoginWd):
        LoginWd.setObjectName("LoginWd")
        LoginWd.setWindowModality(QtCore.Qt.ApplicationModal)
        LoginWd.resize(600, 460)
        LoginWd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.graphicsView = QtWidgets.QGraphicsView(LoginWd)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 600, 250))
        brush = QtGui.QBrush(QtGui.QColor(10, 25, 135, 90))
        brush.setStyle(QtCore.Qt.Dense2Pattern)
        self.graphicsView.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 175, 160))
        brush.setStyle(QtCore.Qt.Dense7Pattern)
        self.graphicsView.setForegroundBrush(brush)
        self.graphicsView.setObjectName("graphicsView")
        self.userNameLabel = QtWidgets.QLabel(LoginWd)
        self.userNameLabel.setGeometry(QtCore.QRect(120, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.userNameLabel.setFont(font)
        self.userNameLabel.setObjectName("userNameLabel")
        self.passwdLabel = QtWidgets.QLabel(LoginWd)
        self.passwdLabel.setGeometry(QtCore.QRect(120, 340, 71, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.passwdLabel.setFont(font)
        self.passwdLabel.setObjectName("passwdLabel")
        self.LoginButton = QtWidgets.QPushButton(LoginWd)
        self.LoginButton.setGeometry(QtCore.QRect(220, 380, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LoginButton.setFont(font)
        self.LoginButton.setObjectName("LoginButton")
        self.userNameInput = QtWidgets.QLineEdit(LoginWd)
        self.userNameInput.setGeometry(QtCore.QRect(190, 290, 291, 31))
        self.userNameInput.setObjectName("userNameInput")
        self.passwdInput = QtWidgets.QLineEdit(LoginWd)
        self.passwdInput.setGeometry(QtCore.QRect(190, 340, 291, 31))
        self.passwdInput.setText("")
        self.passwdInput.setObjectName("passwdInput")
        self.RegisterLabel = QtWidgets.QLabel(LoginWd)
        self.RegisterLabel.setGeometry(QtCore.QRect(430, 390, 54, 12))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.RegisterLabel.setFont(font)
        self.RegisterLabel.setObjectName("RegisterLabel")

        self.retranslateUi(LoginWd)
        QtCore.QMetaObject.connectSlotsByName(LoginWd)

    def retranslateUi(self, LoginWd):
        _translate = QtCore.QCoreApplication.translate
        LoginWd.setWindowTitle(_translate("LoginWd", "Form"))
        self.userNameLabel.setText(_translate("LoginWd", "用户名："))
        self.passwdLabel.setText(_translate("LoginWd", "密  码："))
        self.LoginButton.setText(_translate("LoginWd", "登   录"))
        self.RegisterLabel.setText(_translate("LoginWd", "注册"))
