# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftSide = QtWidgets.QFrame(self.centralwidget)
        self.leftSide.setGeometry(QtCore.QRect(0, 0, 60, 680))
        self.leftSide.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftSide.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftSide.setObjectName("leftSide")
        self.infoWidget = QtWidgets.QWidget(self.centralwidget)
        self.infoWidget.setGeometry(QtCore.QRect(60, 0, 250, 680))
        self.infoWidget.setObjectName("infoWidget")
        self.MsgWidget = QtWidgets.QWidget(self.centralwidget)
        self.MsgWidget.setGeometry(QtCore.QRect(310, 0, 610, 680))
        self.MsgWidget.setObjectName("MsgWidget")
        self.MsgScrollArea = QtWidgets.QScrollArea(self.MsgWidget)
        self.MsgScrollArea.setGeometry(QtCore.QRect(0, 0, 610, 460))
        self.MsgScrollArea.setWidgetResizable(True)
        self.MsgScrollArea.setObjectName("MsgScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 608, 458))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.MsgScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.ToolsLabel = QtWidgets.QLabel(self.MsgWidget)
        self.ToolsLabel.setGeometry(QtCore.QRect(0, 460, 610, 30))
        self.ToolsLabel.setObjectName("ToolsLabel")
        self.InputTextEdit = QtWidgets.QTextEdit(self.MsgWidget)
        self.InputTextEdit.setGeometry(QtCore.QRect(0, 490, 610, 190))
        self.InputTextEdit.setObjectName("InputTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ToolsLabel.setText(_translate("MainWindow", "TextLabel"))
