# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterSuccessUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterSuccess(object):
    def setupUi(self, RegisterSuccess):
        RegisterSuccess.setObjectName("RegisterSuccess")
        RegisterSuccess.resize(361, 154)
        self.label = QtWidgets.QLabel(RegisterSuccess)
        self.label.setGeometry(QtCore.QRect(100, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.closeButton = QtWidgets.QPushButton(RegisterSuccess)
        self.closeButton.setGeometry(QtCore.QRect(120, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.timeMsgLabel = QtWidgets.QLabel(RegisterSuccess)
        self.timeMsgLabel.setGeometry(QtCore.QRect(160, 80, 91, 16))
        self.timeMsgLabel.setObjectName("timeMsgLabel")
        self.timeLabel = QtWidgets.QLabel(RegisterSuccess)
        self.timeLabel.setGeometry(QtCore.QRect(140, 80, 16, 16))
        self.timeLabel.setObjectName("timeLabel")

        self.retranslateUi(RegisterSuccess)
        QtCore.QMetaObject.connectSlotsByName(RegisterSuccess)

    def retranslateUi(self, RegisterSuccess):
        _translate = QtCore.QCoreApplication.translate
        RegisterSuccess.setWindowTitle(_translate("RegisterSuccess", "Dialog"))
        self.label.setText(_translate("RegisterSuccess", "注册成功"))
        self.closeButton.setText(_translate("RegisterSuccess", "关闭"))
        self.timeMsgLabel.setText(_translate("RegisterSuccess", "秒后自动关闭"))
        self.timeLabel.setText(_translate("RegisterSuccess", "5"))
